server:
  port: ${GATEWAY_PORT}

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: HS512

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"

        - id: user-service-docs
          uri: lb://user-service
          predicates:
            - Path=/v3/api-docs/user-service
          filters:
            - RewritePath=/v3/api-docs/user-service, /v3/api-docs

        - id: auth-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 5
                key-resolver: "#{@userKeyResolver}"

        - id: merchant-service
          uri: lb://merchant-service
          predicates:
            - name: Path
              args:
                patterns:
                  - /api/v1/cuisine/**
                  - /api/v1/restaurant/**
                  - /api/v1/restaurant-schedule/**
                  - /api/v1/category/**
                  - /api/v1/product/**
                  - /api/v1/option-group/**
                  - /api/v1/option-item/**
                  - /merchant-images/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 5
                key-resolver: "#{@userKeyResolver}"

        - id: merchant-service-docs
          uri: lb://merchant-service
          predicates:
            - Path=/v3/api-docs/merchant-service
          filters:
            - RewritePath=/v3/api-docs/merchant-service, /v3/api-docs

        - id: order-service
          uri: lb://order-service
          predicates:
            - name: Path
              args:
                patterns:
                  - /api/v1/order/**
                  - /api/v1/review/**
                  - /api/v1/management/order/merchant/**
                  - /api/v1/shipping/order/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 3
                redis-rate-limiter.burstCapacity: 5
                key-resolver: "#{@userKeyResolver}"

        - id: order-service-docs
          uri: lb://order-service
          predicates:
            - Path=/v3/api-docs/order-service
          filters:
            - RewritePath=/v3/api-docs/order-service, /v3/api-docs

        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - name: Path
              args:
                patterns:
                  -
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@userKeyResolver}"

        - id: delivery-service-docs
          uri: lb://delivery-service
          predicates:
            - Path=/v3/api-docs/delivery-service
          filters:
            - RewritePath=/v3/api-docs/delivery-serice, /v3/api-docs

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - name: Path
              args:
                patterns:
                  - /api/v1/notification/**

          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@userKeyResolver}"

        - id: notification-service-docs
          uri: lb://notification-service
          predicates:
            - Path=/v3/api-docs/notification-service
          filters:
            - RewritePath=/v3/api-docs/notification-service, /v3/api-docs
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: merchant-service
        url: /v3/api-docs/merchant-service
      - name: user-service
        url: /v3/api-docs/user-service
      - name: order-service
        url: /v3/api-docs/order-service
      - name: delivery-service
        url: /v3/api-docs/delivery-service
      - name: notification-service
        url: /v3/api-docs/notification-service
  api-docs:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

jwt:
  secret: ${JWT_SECRET}